sudo: false

language: node_js
node_js:
    - "12"

services:
    - docker

notifications:
    email: false

branches:
    only:
        - master

addons:
    apt:
        packages:
            - chromium-browser

cache:
    directories:
        - ./node_modules
        - ./dist

before_script:
    - pushd .. && git clone https://github.com/onosproject/build-tools.git && popd

install:
    - npm install -g @angular/cli
    - npm install

jobs:
    include:
        - stage: tests
          script:
              - make test

